name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - master
    - release/*  # branches matching refs/heads/release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run lint
        npm run dns
        npm run add
        npm run deploy
        # npm run ng -- deploy --base-href=/everything-github-continuous-integration-deployment-and-hosting/ --name="hamza-webhelpmedica" --email=hamza.bedoui@webhelpmedica.com
        ###
        # Configure Angular first!
        ####
        # npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
        # npm run webdriver-update-ci
        # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
        ####
